---
- name: Install nftables
  package:
    name: nftables
    state: present

- name: Deploy nftables config
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: "0640"
  notify: reload nftables

- name: Enable and start nftables
  service:
    name: nftables
    enabled: true
    state: started
